//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.CarRental.Dal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class carfeaturemap
    {
        public int id { get; set; }
        public int id_car { get; set; }
        public int id_carfeature { get; set; }
    
        public virtual car car { get; set; }
        public virtual carfeature carfeature { get; set; }
    }
}
