//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.CarRental.Dal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverslicense
    {
        public int id { get; set; }
        public string licensenumber { get; set; }
        public Nullable<System.DateTime> issuedate { get; set; }
        public int id_driverslicensecategory { get; set; }
    
        public virtual driverslicensecategory driverslicensecategory { get; set; }
    }
}
