//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toci.CarRental.Dal.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentaloption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rentaloption()
        {
            this.rental = new HashSet<rental>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> kilometerlimit { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> rentalinterval { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public int id_client { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rental> rental { get; set; }
    }
}
